/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.15.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTextBrowser>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QPushButton *startbuttom;
    QTextBrowser *IP0_0;
    QTextBrowser *IP0_1;
    QTextBrowser *IP0_2;
    QTextBrowser *IP0_3;
    QTextBrowser *IP1_2;
    QTextBrowser *IP1_3;
    QTextBrowser *IP1_0;
    QTextBrowser *IP1_1;
    QTextBrowser *IP2_1;
    QTextBrowser *IP2_3;
    QTextBrowser *IP2_0;
    QTextBrowser *IP2_2;
    QTextBrowser *IP3_3;
    QTextBrowser *IP3_1;
    QTextBrowser *IP3_0;
    QTextBrowser *IP3_2;
    QTextBrowser *IP4_2;
    QTextBrowser *IP4_0;
    QTextBrowser *IP4_3;
    QTextBrowser *IP4_1;
    QTextBrowser *IP6_0;
    QTextBrowser *IP6_2;
    QTextBrowser *IP8_1;
    QTextBrowser *IP5_3;
    QTextBrowser *IP8_2;
    QTextBrowser *IP6_3;
    QTextBrowser *IP6_1;
    QTextBrowser *IP9_1;
    QTextBrowser *IP7_0;
    QTextBrowser *IP8_0;
    QTextBrowser *IP5_0;
    QTextBrowser *IP9_2;
    QTextBrowser *IP5_1;
    QTextBrowser *IP7_1;
    QTextBrowser *IP9_3;
    QTextBrowser *IP7_2;
    QTextBrowser *IP8_3;
    QTextBrowser *IP7_3;
    QTextBrowser *IP9_0;
    QTextBrowser *IP5_2;
    QTextBrowser *IP0_4;
    QTextBrowser *IP4_4;
    QTextBrowser *IP1_4;
    QTextBrowser *IP2_4;
    QTextBrowser *IP3_4;
    QTextBrowser *IP9_4;
    QTextBrowser *IP6_4;
    QTextBrowser *IP5_4;
    QTextBrowser *IP8_4;
    QTextBrowser *IP7_4;
    QCheckBox *IP0;
    QCheckBox *IP1;
    QCheckBox *IP2;
    QCheckBox *IP3;
    QCheckBox *IP4;
    QCheckBox *IP8;
    QCheckBox *IP9;
    QCheckBox *IP7;
    QCheckBox *IP6;
    QCheckBox *IP5;
    QLabel *connect0;
    QLabel *connect1;
    QLabel *connect2;
    QLabel *connect3;
    QLabel *connect4;
    QLabel *connect7;
    QLabel *connect8;
    QLabel *connect9;
    QLabel *connect5;
    QLabel *connect6;
    QTextBrowser *IP0_5;
    QTextBrowser *IP0_6;
    QTextBrowser *IP0_7;
    QTextBrowser *IP1_5;
    QTextBrowser *IP1_6;
    QTextBrowser *IP1_7;
    QTextBrowser *IP2_5;
    QTextBrowser *IP2_6;
    QTextBrowser *IP2_7;
    QTextBrowser *IP3_5;
    QTextBrowser *IP3_6;
    QTextBrowser *IP3_7;
    QTextBrowser *IP4_5;
    QTextBrowser *IP4_6;
    QTextBrowser *IP4_7;
    QTextBrowser *IP5_5;
    QTextBrowser *IP5_6;
    QTextBrowser *IP5_7;
    QTextBrowser *IP6_5;
    QTextBrowser *IP6_6;
    QTextBrowser *IP6_7;
    QTextBrowser *IP7_5;
    QTextBrowser *IP7_6;
    QTextBrowser *IP7_7;
    QTextBrowser *IP8_5;
    QTextBrowser *IP8_6;
    QTextBrowser *IP8_7;
    QTextBrowser *IP9_5;
    QTextBrowser *IP9_6;
    QTextBrowser *IP9_7;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(932, 525);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        startbuttom = new QPushButton(centralwidget);
        startbuttom->setObjectName(QString::fromUtf8("startbuttom"));
        startbuttom->setGeometry(QRect(20, 10, 89, 25));
        IP0_0 = new QTextBrowser(centralwidget);
        IP0_0->setObjectName(QString::fromUtf8("IP0_0"));
        IP0_0->setGeometry(QRect(70, 50, 81, 31));
        IP0_1 = new QTextBrowser(centralwidget);
        IP0_1->setObjectName(QString::fromUtf8("IP0_1"));
        IP0_1->setGeometry(QRect(160, 50, 81, 31));
        IP0_2 = new QTextBrowser(centralwidget);
        IP0_2->setObjectName(QString::fromUtf8("IP0_2"));
        IP0_2->setGeometry(QRect(250, 50, 81, 31));
        IP0_3 = new QTextBrowser(centralwidget);
        IP0_3->setObjectName(QString::fromUtf8("IP0_3"));
        IP0_3->setGeometry(QRect(340, 50, 81, 31));
        IP1_2 = new QTextBrowser(centralwidget);
        IP1_2->setObjectName(QString::fromUtf8("IP1_2"));
        IP1_2->setGeometry(QRect(250, 90, 81, 31));
        IP1_3 = new QTextBrowser(centralwidget);
        IP1_3->setObjectName(QString::fromUtf8("IP1_3"));
        IP1_3->setGeometry(QRect(340, 90, 81, 31));
        IP1_0 = new QTextBrowser(centralwidget);
        IP1_0->setObjectName(QString::fromUtf8("IP1_0"));
        IP1_0->setGeometry(QRect(70, 90, 81, 31));
        IP1_1 = new QTextBrowser(centralwidget);
        IP1_1->setObjectName(QString::fromUtf8("IP1_1"));
        IP1_1->setGeometry(QRect(160, 90, 81, 31));
        IP2_1 = new QTextBrowser(centralwidget);
        IP2_1->setObjectName(QString::fromUtf8("IP2_1"));
        IP2_1->setGeometry(QRect(160, 130, 81, 31));
        IP2_3 = new QTextBrowser(centralwidget);
        IP2_3->setObjectName(QString::fromUtf8("IP2_3"));
        IP2_3->setGeometry(QRect(340, 130, 81, 31));
        IP2_0 = new QTextBrowser(centralwidget);
        IP2_0->setObjectName(QString::fromUtf8("IP2_0"));
        IP2_0->setGeometry(QRect(70, 130, 81, 31));
        IP2_2 = new QTextBrowser(centralwidget);
        IP2_2->setObjectName(QString::fromUtf8("IP2_2"));
        IP2_2->setGeometry(QRect(250, 130, 81, 31));
        IP3_3 = new QTextBrowser(centralwidget);
        IP3_3->setObjectName(QString::fromUtf8("IP3_3"));
        IP3_3->setGeometry(QRect(340, 170, 81, 31));
        IP3_1 = new QTextBrowser(centralwidget);
        IP3_1->setObjectName(QString::fromUtf8("IP3_1"));
        IP3_1->setGeometry(QRect(160, 170, 81, 31));
        IP3_0 = new QTextBrowser(centralwidget);
        IP3_0->setObjectName(QString::fromUtf8("IP3_0"));
        IP3_0->setGeometry(QRect(70, 170, 81, 31));
        IP3_2 = new QTextBrowser(centralwidget);
        IP3_2->setObjectName(QString::fromUtf8("IP3_2"));
        IP3_2->setGeometry(QRect(250, 170, 81, 31));
        IP4_2 = new QTextBrowser(centralwidget);
        IP4_2->setObjectName(QString::fromUtf8("IP4_2"));
        IP4_2->setGeometry(QRect(250, 210, 81, 31));
        IP4_0 = new QTextBrowser(centralwidget);
        IP4_0->setObjectName(QString::fromUtf8("IP4_0"));
        IP4_0->setGeometry(QRect(70, 210, 81, 31));
        IP4_3 = new QTextBrowser(centralwidget);
        IP4_3->setObjectName(QString::fromUtf8("IP4_3"));
        IP4_3->setGeometry(QRect(340, 210, 81, 31));
        IP4_1 = new QTextBrowser(centralwidget);
        IP4_1->setObjectName(QString::fromUtf8("IP4_1"));
        IP4_1->setGeometry(QRect(160, 210, 81, 31));
        IP6_0 = new QTextBrowser(centralwidget);
        IP6_0->setObjectName(QString::fromUtf8("IP6_0"));
        IP6_0->setGeometry(QRect(70, 290, 81, 31));
        IP6_2 = new QTextBrowser(centralwidget);
        IP6_2->setObjectName(QString::fromUtf8("IP6_2"));
        IP6_2->setGeometry(QRect(340, 290, 81, 31));
        IP8_1 = new QTextBrowser(centralwidget);
        IP8_1->setObjectName(QString::fromUtf8("IP8_1"));
        IP8_1->setGeometry(QRect(160, 370, 81, 31));
        IP5_3 = new QTextBrowser(centralwidget);
        IP5_3->setObjectName(QString::fromUtf8("IP5_3"));
        IP5_3->setGeometry(QRect(340, 250, 81, 31));
        IP8_2 = new QTextBrowser(centralwidget);
        IP8_2->setObjectName(QString::fromUtf8("IP8_2"));
        IP8_2->setGeometry(QRect(250, 370, 81, 31));
        IP6_3 = new QTextBrowser(centralwidget);
        IP6_3->setObjectName(QString::fromUtf8("IP6_3"));
        IP6_3->setGeometry(QRect(250, 290, 81, 31));
        IP6_1 = new QTextBrowser(centralwidget);
        IP6_1->setObjectName(QString::fromUtf8("IP6_1"));
        IP6_1->setGeometry(QRect(160, 290, 81, 31));
        IP9_1 = new QTextBrowser(centralwidget);
        IP9_1->setObjectName(QString::fromUtf8("IP9_1"));
        IP9_1->setGeometry(QRect(160, 410, 81, 31));
        IP7_0 = new QTextBrowser(centralwidget);
        IP7_0->setObjectName(QString::fromUtf8("IP7_0"));
        IP7_0->setGeometry(QRect(70, 330, 81, 31));
        IP8_0 = new QTextBrowser(centralwidget);
        IP8_0->setObjectName(QString::fromUtf8("IP8_0"));
        IP8_0->setGeometry(QRect(70, 370, 81, 31));
        IP5_0 = new QTextBrowser(centralwidget);
        IP5_0->setObjectName(QString::fromUtf8("IP5_0"));
        IP5_0->setGeometry(QRect(70, 250, 81, 31));
        IP9_2 = new QTextBrowser(centralwidget);
        IP9_2->setObjectName(QString::fromUtf8("IP9_2"));
        IP9_2->setGeometry(QRect(250, 410, 81, 31));
        IP5_1 = new QTextBrowser(centralwidget);
        IP5_1->setObjectName(QString::fromUtf8("IP5_1"));
        IP5_1->setGeometry(QRect(160, 250, 81, 31));
        IP7_1 = new QTextBrowser(centralwidget);
        IP7_1->setObjectName(QString::fromUtf8("IP7_1"));
        IP7_1->setGeometry(QRect(160, 330, 81, 31));
        IP9_3 = new QTextBrowser(centralwidget);
        IP9_3->setObjectName(QString::fromUtf8("IP9_3"));
        IP9_3->setGeometry(QRect(340, 410, 81, 31));
        IP7_2 = new QTextBrowser(centralwidget);
        IP7_2->setObjectName(QString::fromUtf8("IP7_2"));
        IP7_2->setGeometry(QRect(250, 330, 81, 31));
        IP8_3 = new QTextBrowser(centralwidget);
        IP8_3->setObjectName(QString::fromUtf8("IP8_3"));
        IP8_3->setGeometry(QRect(340, 370, 81, 31));
        IP7_3 = new QTextBrowser(centralwidget);
        IP7_3->setObjectName(QString::fromUtf8("IP7_3"));
        IP7_3->setGeometry(QRect(340, 330, 81, 31));
        IP9_0 = new QTextBrowser(centralwidget);
        IP9_0->setObjectName(QString::fromUtf8("IP9_0"));
        IP9_0->setGeometry(QRect(70, 410, 81, 31));
        IP5_2 = new QTextBrowser(centralwidget);
        IP5_2->setObjectName(QString::fromUtf8("IP5_2"));
        IP5_2->setGeometry(QRect(250, 250, 81, 31));
        IP0_4 = new QTextBrowser(centralwidget);
        IP0_4->setObjectName(QString::fromUtf8("IP0_4"));
        IP0_4->setGeometry(QRect(430, 50, 81, 31));
        IP4_4 = new QTextBrowser(centralwidget);
        IP4_4->setObjectName(QString::fromUtf8("IP4_4"));
        IP4_4->setGeometry(QRect(430, 210, 81, 31));
        IP1_4 = new QTextBrowser(centralwidget);
        IP1_4->setObjectName(QString::fromUtf8("IP1_4"));
        IP1_4->setGeometry(QRect(430, 90, 81, 31));
        IP2_4 = new QTextBrowser(centralwidget);
        IP2_4->setObjectName(QString::fromUtf8("IP2_4"));
        IP2_4->setGeometry(QRect(430, 130, 81, 31));
        IP3_4 = new QTextBrowser(centralwidget);
        IP3_4->setObjectName(QString::fromUtf8("IP3_4"));
        IP3_4->setGeometry(QRect(430, 170, 81, 31));
        IP9_4 = new QTextBrowser(centralwidget);
        IP9_4->setObjectName(QString::fromUtf8("IP9_4"));
        IP9_4->setGeometry(QRect(430, 410, 81, 31));
        IP6_4 = new QTextBrowser(centralwidget);
        IP6_4->setObjectName(QString::fromUtf8("IP6_4"));
        IP6_4->setGeometry(QRect(430, 290, 81, 31));
        IP5_4 = new QTextBrowser(centralwidget);
        IP5_4->setObjectName(QString::fromUtf8("IP5_4"));
        IP5_4->setGeometry(QRect(430, 250, 81, 31));
        IP8_4 = new QTextBrowser(centralwidget);
        IP8_4->setObjectName(QString::fromUtf8("IP8_4"));
        IP8_4->setGeometry(QRect(430, 370, 81, 31));
        IP7_4 = new QTextBrowser(centralwidget);
        IP7_4->setObjectName(QString::fromUtf8("IP7_4"));
        IP7_4->setGeometry(QRect(430, 330, 81, 31));
        IP0 = new QCheckBox(centralwidget);
        IP0->setObjectName(QString::fromUtf8("IP0"));
        IP0->setGeometry(QRect(10, 50, 92, 23));
        IP0->setText(QString::fromUtf8("IP0"));
        IP0->setChecked(false);
        IP1 = new QCheckBox(centralwidget);
        IP1->setObjectName(QString::fromUtf8("IP1"));
        IP1->setGeometry(QRect(10, 90, 92, 23));
        IP2 = new QCheckBox(centralwidget);
        IP2->setObjectName(QString::fromUtf8("IP2"));
        IP2->setGeometry(QRect(10, 130, 92, 23));
        IP3 = new QCheckBox(centralwidget);
        IP3->setObjectName(QString::fromUtf8("IP3"));
        IP3->setGeometry(QRect(10, 170, 92, 23));
        IP4 = new QCheckBox(centralwidget);
        IP4->setObjectName(QString::fromUtf8("IP4"));
        IP4->setGeometry(QRect(10, 210, 92, 23));
        IP8 = new QCheckBox(centralwidget);
        IP8->setObjectName(QString::fromUtf8("IP8"));
        IP8->setGeometry(QRect(10, 370, 92, 23));
        IP9 = new QCheckBox(centralwidget);
        IP9->setObjectName(QString::fromUtf8("IP9"));
        IP9->setGeometry(QRect(10, 410, 92, 23));
        IP7 = new QCheckBox(centralwidget);
        IP7->setObjectName(QString::fromUtf8("IP7"));
        IP7->setGeometry(QRect(10, 330, 92, 23));
        IP6 = new QCheckBox(centralwidget);
        IP6->setObjectName(QString::fromUtf8("IP6"));
        IP6->setGeometry(QRect(10, 290, 92, 23));
        IP5 = new QCheckBox(centralwidget);
        IP5->setObjectName(QString::fromUtf8("IP5"));
        IP5->setGeometry(QRect(10, 250, 92, 23));
        connect0 = new QLabel(centralwidget);
        connect0->setObjectName(QString::fromUtf8("connect0"));
        connect0->setGeometry(QRect(800, 50, 91, 17));
        connect1 = new QLabel(centralwidget);
        connect1->setObjectName(QString::fromUtf8("connect1"));
        connect1->setGeometry(QRect(800, 90, 91, 17));
        connect2 = new QLabel(centralwidget);
        connect2->setObjectName(QString::fromUtf8("connect2"));
        connect2->setGeometry(QRect(800, 130, 91, 17));
        connect3 = new QLabel(centralwidget);
        connect3->setObjectName(QString::fromUtf8("connect3"));
        connect3->setGeometry(QRect(800, 170, 91, 17));
        connect4 = new QLabel(centralwidget);
        connect4->setObjectName(QString::fromUtf8("connect4"));
        connect4->setGeometry(QRect(800, 210, 91, 17));
        connect7 = new QLabel(centralwidget);
        connect7->setObjectName(QString::fromUtf8("connect7"));
        connect7->setGeometry(QRect(800, 330, 91, 17));
        connect8 = new QLabel(centralwidget);
        connect8->setObjectName(QString::fromUtf8("connect8"));
        connect8->setGeometry(QRect(800, 370, 91, 17));
        connect9 = new QLabel(centralwidget);
        connect9->setObjectName(QString::fromUtf8("connect9"));
        connect9->setGeometry(QRect(800, 410, 91, 17));
        connect5 = new QLabel(centralwidget);
        connect5->setObjectName(QString::fromUtf8("connect5"));
        connect5->setGeometry(QRect(800, 250, 91, 17));
        connect6 = new QLabel(centralwidget);
        connect6->setObjectName(QString::fromUtf8("connect6"));
        connect6->setGeometry(QRect(800, 290, 91, 17));
        IP0_5 = new QTextBrowser(centralwidget);
        IP0_5->setObjectName(QString::fromUtf8("IP0_5"));
        IP0_5->setGeometry(QRect(520, 50, 81, 31));
        IP0_6 = new QTextBrowser(centralwidget);
        IP0_6->setObjectName(QString::fromUtf8("IP0_6"));
        IP0_6->setGeometry(QRect(610, 50, 81, 31));
        IP0_7 = new QTextBrowser(centralwidget);
        IP0_7->setObjectName(QString::fromUtf8("IP0_7"));
        IP0_7->setGeometry(QRect(700, 50, 81, 31));
        IP1_5 = new QTextBrowser(centralwidget);
        IP1_5->setObjectName(QString::fromUtf8("IP1_5"));
        IP1_5->setGeometry(QRect(520, 90, 81, 31));
        IP1_6 = new QTextBrowser(centralwidget);
        IP1_6->setObjectName(QString::fromUtf8("IP1_6"));
        IP1_6->setGeometry(QRect(610, 90, 81, 31));
        IP1_7 = new QTextBrowser(centralwidget);
        IP1_7->setObjectName(QString::fromUtf8("IP1_7"));
        IP1_7->setGeometry(QRect(700, 90, 81, 31));
        IP2_5 = new QTextBrowser(centralwidget);
        IP2_5->setObjectName(QString::fromUtf8("IP2_5"));
        IP2_5->setGeometry(QRect(520, 130, 81, 31));
        IP2_6 = new QTextBrowser(centralwidget);
        IP2_6->setObjectName(QString::fromUtf8("IP2_6"));
        IP2_6->setGeometry(QRect(610, 130, 81, 31));
        IP2_7 = new QTextBrowser(centralwidget);
        IP2_7->setObjectName(QString::fromUtf8("IP2_7"));
        IP2_7->setGeometry(QRect(700, 130, 81, 31));
        IP3_5 = new QTextBrowser(centralwidget);
        IP3_5->setObjectName(QString::fromUtf8("IP3_5"));
        IP3_5->setGeometry(QRect(520, 170, 81, 31));
        IP3_6 = new QTextBrowser(centralwidget);
        IP3_6->setObjectName(QString::fromUtf8("IP3_6"));
        IP3_6->setGeometry(QRect(610, 170, 81, 31));
        IP3_7 = new QTextBrowser(centralwidget);
        IP3_7->setObjectName(QString::fromUtf8("IP3_7"));
        IP3_7->setGeometry(QRect(700, 170, 81, 31));
        IP4_5 = new QTextBrowser(centralwidget);
        IP4_5->setObjectName(QString::fromUtf8("IP4_5"));
        IP4_5->setGeometry(QRect(520, 210, 81, 31));
        IP4_6 = new QTextBrowser(centralwidget);
        IP4_6->setObjectName(QString::fromUtf8("IP4_6"));
        IP4_6->setGeometry(QRect(610, 210, 81, 31));
        IP4_7 = new QTextBrowser(centralwidget);
        IP4_7->setObjectName(QString::fromUtf8("IP4_7"));
        IP4_7->setGeometry(QRect(700, 210, 81, 31));
        IP5_5 = new QTextBrowser(centralwidget);
        IP5_5->setObjectName(QString::fromUtf8("IP5_5"));
        IP5_5->setGeometry(QRect(520, 250, 81, 31));
        IP5_6 = new QTextBrowser(centralwidget);
        IP5_6->setObjectName(QString::fromUtf8("IP5_6"));
        IP5_6->setGeometry(QRect(610, 250, 81, 31));
        IP5_7 = new QTextBrowser(centralwidget);
        IP5_7->setObjectName(QString::fromUtf8("IP5_7"));
        IP5_7->setGeometry(QRect(700, 250, 81, 31));
        IP6_5 = new QTextBrowser(centralwidget);
        IP6_5->setObjectName(QString::fromUtf8("IP6_5"));
        IP6_5->setGeometry(QRect(520, 290, 81, 31));
        IP6_6 = new QTextBrowser(centralwidget);
        IP6_6->setObjectName(QString::fromUtf8("IP6_6"));
        IP6_6->setGeometry(QRect(610, 290, 81, 31));
        IP6_7 = new QTextBrowser(centralwidget);
        IP6_7->setObjectName(QString::fromUtf8("IP6_7"));
        IP6_7->setGeometry(QRect(700, 290, 81, 31));
        IP7_5 = new QTextBrowser(centralwidget);
        IP7_5->setObjectName(QString::fromUtf8("IP7_5"));
        IP7_5->setGeometry(QRect(520, 330, 81, 31));
        IP7_6 = new QTextBrowser(centralwidget);
        IP7_6->setObjectName(QString::fromUtf8("IP7_6"));
        IP7_6->setGeometry(QRect(610, 330, 81, 31));
        IP7_7 = new QTextBrowser(centralwidget);
        IP7_7->setObjectName(QString::fromUtf8("IP7_7"));
        IP7_7->setGeometry(QRect(700, 330, 81, 31));
        IP8_5 = new QTextBrowser(centralwidget);
        IP8_5->setObjectName(QString::fromUtf8("IP8_5"));
        IP8_5->setGeometry(QRect(520, 370, 81, 31));
        IP8_6 = new QTextBrowser(centralwidget);
        IP8_6->setObjectName(QString::fromUtf8("IP8_6"));
        IP8_6->setGeometry(QRect(610, 370, 81, 31));
        IP8_7 = new QTextBrowser(centralwidget);
        IP8_7->setObjectName(QString::fromUtf8("IP8_7"));
        IP8_7->setGeometry(QRect(700, 370, 81, 31));
        IP9_5 = new QTextBrowser(centralwidget);
        IP9_5->setObjectName(QString::fromUtf8("IP9_5"));
        IP9_5->setGeometry(QRect(520, 410, 81, 31));
        IP9_6 = new QTextBrowser(centralwidget);
        IP9_6->setObjectName(QString::fromUtf8("IP9_6"));
        IP9_6->setGeometry(QRect(610, 410, 81, 31));
        IP9_7 = new QTextBrowser(centralwidget);
        IP9_7->setObjectName(QString::fromUtf8("IP9_7"));
        IP9_7->setGeometry(QRect(700, 410, 81, 31));
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 932, 26));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MainWindow", nullptr));
        startbuttom->setText(QCoreApplication::translate("MainWindow", "Start", nullptr));
        IP1->setText(QCoreApplication::translate("MainWindow", "IP1", nullptr));
        IP2->setText(QCoreApplication::translate("MainWindow", "IP2", nullptr));
        IP3->setText(QCoreApplication::translate("MainWindow", "IP3", nullptr));
        IP4->setText(QCoreApplication::translate("MainWindow", "IP4", nullptr));
        IP8->setText(QCoreApplication::translate("MainWindow", "IP8", nullptr));
        IP9->setText(QCoreApplication::translate("MainWindow", "IP9", nullptr));
        IP7->setText(QCoreApplication::translate("MainWindow", "IP7", nullptr));
        IP6->setText(QCoreApplication::translate("MainWindow", "IP6", nullptr));
        IP5->setText(QCoreApplication::translate("MainWindow", "IP5", nullptr));
        connect0->setText(QCoreApplication::translate("MainWindow", "not connect", nullptr));
        connect1->setText(QCoreApplication::translate("MainWindow", "not connect", nullptr));
        connect2->setText(QCoreApplication::translate("MainWindow", "not connect", nullptr));
        connect3->setText(QCoreApplication::translate("MainWindow", "not connect", nullptr));
        connect4->setText(QCoreApplication::translate("MainWindow", "not connect", nullptr));
        connect7->setText(QCoreApplication::translate("MainWindow", "not connect", nullptr));
        connect8->setText(QCoreApplication::translate("MainWindow", "not connect", nullptr));
        connect9->setText(QCoreApplication::translate("MainWindow", "not connect", nullptr));
        connect5->setText(QCoreApplication::translate("MainWindow", "not connect", nullptr));
        connect6->setText(QCoreApplication::translate("MainWindow", "not connect", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
